### ISSUE TITLE
Website -> Use CSS -> .style result not showing

### ISSUE THREAD

**Issue by Falke-Design** [graphery/graphery#2]
The `.style` examples are not rendered

![result_not_loading](https://user-images.githubusercontent.com/19800037/98800324-8686f400-2410-11eb-8d62-16a9daf5c39a.PNG)

Firefox 82.0.3
Windows

**Comment by pabloalmunia** [comment]
Confirmed, it is a mistake in these examples. Firefox needs a measurement for the styles `x`, `y`, `width`, and `height`. Interestingly, it works well in Chrome, but it is a mandatory measurement.

The documentation has been updated, and this error is fixed. Please, reload the page with Ctrl+F5 or Cmd+R for seeing the updated page.

https://www.graphery.org/svg/guide/13-CSS.html

**Comment by Falke-Design** [comment]
Is working now 👍
