### ISSUE TITLE
Order of elements

### ISSUE THREAD

**Issue by Johnz86** [graphery/graphery#3]
In svg oder of display is based on order of the dom elements. In css it is the z-index.
Normaly I would do: 
```
function raise(targetElement){
  let parent = targetElement.ownerSVGElement;
  parent.appendChild(targetElement);
}
```
What can I do to rearange the elements with graphery?

**Comment by pabloalmunia** [comment]
Good question. We have two ways of doing this.

**Keep the `raise()` function as it is**

We can to pass the native element to the function:

```js
raise(mySVGObj.el);
```

**Adapt the `raise()` function to Graphery SVG**

We usually will only have to change elements in the parent element, and we can use something like

```js
function raise(targetElement) {
  const t = gySVG(targetElement);
  t.attachTo(t.parent());
}
```

Also we can search the SVG parent element with '.ownerSVGElement()`:

```js
function raise(targetElement){
  const t = gySVG(targetElement);
  t.attachTo(t.ownerSVGElement());
}
```

If we are sure that we are going to receive a gySVG object, then we can remove this line:

```js
//  const t = gySVG(targetElement);
```

The next is a complete example. When the user clicks over a shape, this is moved to the foreground:

```html
<div id="content"></div>
<script>
  const svg    = gySVG().viewBox(0, 0, 100, 100).width(50).height(50);
  const circle = svg.add('circle').cx(50).cy(50).r(40).fill('#0000D8');
  const rect   = svg.add('rect').x(50).x(50).width(50).height(50).fill('#D80000');
  circle.addEventListener('click', function () {
    raise(this);
  });
  rect.addEventListener('click', function () {
    raise(this);
  });
  svg.attachTo('#content');

  function raise(targetElement){
    const t = gySVG(targetElement);
    t.attachTo(t.parent());
  }
</script>
```

*More info*: https://www.graphery.org/svg/guide/14-Manage-elements.html

**Comment by Johnz86** [comment]
Thanks for the answer. I used this code:
```
function raise(targetElement) {
  const t = gySVG(targetElement);
  t.attachTo(t.parent());
}
```
This moves the existing element to the bottom of the DOM of parent, which causes it to display as top svg element from all children.

Some API/plugin/feature for controlling the order of the elements would be nice.
